version: '3'
services:
  # postgres:
  #   image: postgres
  #   container_name: go_demo_postgres
  #   volumes:
  #     - ./database_data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_DB: $PGDATABASE
  #     POSTGRES_USER: $PGUSER
  #     POSTGRES_PASSWORD: $PGPASSWORD
  #   stdin_open: true
  #   tty: true

  go-demo:
    restart: always
    # depends_on:
    #   - postgres
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      # CGO_ENABLED: 0
      # GOOS: linux
      # GOARCH: amd64
    build:
      context: .
